const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SIGN_START: "GOOGLE_SIGN_START",
  SIGN_SUCCESS: "SIGN_SUCCESS",
  SIGN_FAILURE: "SIGN_FAILURE",
  EMAIL_SIGN_START: "EMAIL_SIGN_START",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
};

export default UserActionTypes;
